<?php
        try {
            $a = 1;
        } catch (\Exception $e) {
            return array();
        }
?>